import assert from "node:assert/strict";
import { chmod, lstat, mkdtemp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { verifyInAuditSandbox } from "../skills/kyw-audit/scripts/verify.mjs";

async function fixture(t) {
  const base = await mkdtemp(path.join(tmpdir(), "kyw-audit-test-"));
  const repositoryRoot = path.join(base, "source");
  const temporaryParent = path.join(base, "temporary");
  await mkdir(repositoryRoot);
  await mkdir(temporaryParent);
  await writeFile(path.join(repositoryRoot, "test.mjs"), "console.log('source');\n");
  await writeFile(path.join(repositoryRoot, "user-draft.md"), "preserve me\n");
  t.after(() => rm(base, { recursive: true, force: true }));
  return { repositoryRoot, temporaryParent, files: ["test.mjs"], command: ["node", "test.mjs"] };
}

function fakeDocker(run) {
  const calls = [];
  const runner = async (executable, args, options) => {
    calls.push({ executable, args, options });
    assert.equal(executable, "docker");
    assert.equal(options.env, undefined);
    if (args[0] === "image") return { stdout: `sha256:${"a".repeat(64)}\n`, stderr: "" };
    if (args[0] === "run") return run(args);
    if (args[1] === "inspect") return { stdout: args.at(-1), stderr: "" };
    return { stdout: "", stderr: "" };
  };
  return { runner, calls };
}

test("audit sandbox preserves source and unknown files, constrains execution, cleans only its copy", async (t) => {
  const options = await fixture(t);
  const untouched = path.join(options.temporaryParent, "user-owned");
  await mkdir(untouched);
  await writeFile(path.join(untouched, "note"), "unrelated");
  let workspace;
  const docker = fakeDocker(async (args) => {
    const mount = args[args.indexOf("--mount") + 1];
    workspace = mount.slice("type=bind,source=".length, -",target=/work".length);
    assert.notEqual(workspace, options.repositoryRoot);
    for (const flag of ["--pull=never", "--network=none", "--read-only", "--cap-drop=ALL",
      "--security-opt=no-new-privileges", "--user=1000:1000"]) assert.ok(args.includes(flag));
    assert.deepEqual(await readdir(workspace), ["test.mjs"]);
    await writeFile(path.join(workspace, "test.mjs"), "test changed its copy");
    await writeFile(path.join(workspace, "generated"), "generated by test");
    return { stdout: "pass", stderr: "" };
  });
  const result = await verifyInAuditSandbox({ ...options, runner: docker.runner });
  assert.equal(result.status, "PASSED");
  assert.equal(await readFile(path.join(options.repositoryRoot, "test.mjs"), "utf8"), "console.log('source');\n");
  assert.equal(await readFile(path.join(options.repositoryRoot, "user-draft.md"), "utf8"), "preserve me\n");
  assert.equal(await readFile(path.join(untouched, "note"), "utf8"), "unrelated");
  await assert.rejects(readFile(path.join(workspace, "test.mjs")), { code: "ENOENT" });
  assert.equal(docker.calls.filter(({ args }) => args[0] === "run").length, 1);
  assert.equal(docker.calls.at(-1).args[1], "rm");
});

test("unavailable sandbox reports unexecuted verification and never falls back to host tests", async (t) => {
  const options = await fixture(t);
  let calls = 0;
  const result = await verifyInAuditSandbox({ ...options, runner: async () => { calls += 1; throw new Error("no docker"); } });
  assert.equal(result.status, "UNAVAILABLE");
  assert.equal(result.executed, false);
  assert.equal(calls, 1);
  assert.deepEqual(await readdir(options.temporaryParent), []);
});

test("audit copy preserves source executable bits for reviewed CLI tests", async (t) => {
  const options = await fixture(t);
  const source = path.join(options.repositoryRoot, "test.mjs");
  await chmod(source, 0o755);
  const sourceMode = (await lstat(source)).mode;
  const docker = fakeDocker(async (args) => {
    const mount = args[args.indexOf("--mount") + 1];
    const workspace = mount.slice("type=bind,source=".length, -",target=/work".length);
    assert.equal((await lstat(path.join(workspace, "test.mjs"))).mode & 0o111, sourceMode & 0o111);
    return { stdout: "pass", stderr: "" };
  });
  assert.equal((await verifyInAuditSandbox({ ...options, runner: docker.runner })).status, "PASSED");
  assert.equal((await lstat(source)).mode, sourceMode);
});

test("audit rejects escapes, credential files, duplicate inputs and option injection before executing", async (t) => {
  const options = await fixture(t);
  let calls = 0;
  const runner = async () => { calls += 1; throw new Error("unexpected execution"); };
  for (const files of [["../test.mjs"], ["C:/secret"], [".env"], [".npmrc"], [".git/config"],
    ["nested/private.key"], ["test.mjs", "test.mjs"], []]) {
    await assert.rejects(verifyInAuditSandbox({ ...options, files, runner }));
  }
  await assert.rejects(verifyInAuditSandbox({ ...options, image: "--privileged", runner }));
  assert.equal(calls, 0);
});

test("failed isolated tests retain failure and clean the owned container and temporary copy", async (t) => {
  const options = await fixture(t);
  const docker = fakeDocker(async () => { throw Object.assign(new Error("test failed"), { stderr: "assertion failed" }); });
  const result = await verifyInAuditSandbox({ ...options, runner: docker.runner });
  assert.equal(result.status, "BLOCKED");
  assert.equal(result.stderr, "assertion failed");
  assert.deepEqual(await readdir(options.temporaryParent), []);
  assert.equal(docker.calls.at(-1).args[1], "rm");
});

test("unknown container ownership blocks cleanup rather than deleting an unrelated container", async (t) => {
  const options = await fixture(t);
  const docker = fakeDocker(async () => ({ stdout: "pass" }));
  const runner = (exe, args, config) => args[0] === "container" && args[1] === "inspect"
    ? Promise.resolve({ stdout: "someone-else" }) : docker.runner(exe, args, config);
  await assert.rejects(verifyInAuditSandbox({ ...options, runner }), /ownership changed/);
  assert.equal(docker.calls.some(({ args }) => args[1] === "rm"), false);
  assert.equal((await readdir(options.temporaryParent)).length, 1);
});
